// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mbeNote.Infrastructure.Data;

#nullable disable

namespace mbeNote.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317211030_AddPushSubscriptions")]
    partial class AddPushSubscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("mbeNote.Core.Models.CalendarConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalendarId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedAccessToken")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedRefreshToken")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SyncEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique();

                    b.ToTable("CalendarConnections");
                });

            modelBuilder.Entity("mbeNote.Core.Models.PushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Endpoint")
                        .IsUnique();

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("mbeNote.Core.Models.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleCalendarEventId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("NotificationChannels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotificationOffsets")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutlookEventId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RecurrenceEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecurrenceRule")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SnoozeCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SnoozedUntil")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "StartDateTime");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("mbeNote.Core.Models.ReminderCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ReminderCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#3b82f6",
                            Icon = "briefcase",
                            IsSystem = true,
                            Name = "Trabajo"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#8b5cf6",
                            Icon = "user",
                            IsSystem = true,
                            Name = "Personal"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#ef4444",
                            Icon = "heart",
                            IsSystem = true,
                            Name = "Salud"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#22c55e",
                            Icon = "wallet",
                            IsSystem = true,
                            Name = "Finanzas"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#f59e0b",
                            Icon = "users",
                            IsSystem = true,
                            Name = "Reunión"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#ec4899",
                            Icon = "clock",
                            IsSystem = true,
                            Name = "Deadline"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#06b6d4",
                            Icon = "repeat",
                            IsSystem = true,
                            Name = "Hábito"
                        });
                });

            modelBuilder.Entity("mbeNote.Core.Models.ReminderHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewState")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousState")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReminderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReminderId");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("ReminderHistory");
                });

            modelBuilder.Entity("mbeNote.Core.Models.ReminderNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReminderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReminderId");

                    b.HasIndex("UserId", "ReadAt");

                    b.HasIndex("UserId", "ScheduledAt");

                    b.ToTable("ReminderNotifications");
                });

            modelBuilder.Entity("mbeNote.Core.Models.ReminderShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Permission")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReminderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SharedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SharedWithUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SharedWithUserId");

                    b.HasIndex("ReminderId", "SharedWithUserId")
                        .IsUnique();

                    b.ToTable("ReminderShares");
                });

            modelBuilder.Entity("mbeNote.Core.Models.ReminderTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NotificationChannels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotificationOffsets")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecurrenceRule")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("ReminderTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 5,
                            Description = "Reunión diaria de equipo",
                            IsSystem = true,
                            Name = "Daily Standup",
                            NotificationChannels = 1,
                            NotificationOffsets = "[15]",
                            Priority = 1,
                            RecurrenceRule = "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Revisar objetivos y planificar semana",
                            IsSystem = true,
                            Name = "Revisión Semanal",
                            NotificationChannels = 1,
                            NotificationOffsets = "[15]",
                            Priority = 2,
                            RecurrenceRule = "FREQ=WEEKLY;BYDAY=FR"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            Description = "Recordatorio de pago mensual",
                            IsSystem = true,
                            Name = "Pago Mensual",
                            NotificationChannels = 1,
                            NotificationOffsets = "[15]",
                            Priority = 2,
                            RecurrenceRule = "FREQ=MONTHLY;BYMONTHDAY=1"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Recordatorio para hidratarse",
                            IsSystem = true,
                            Name = "Beber Agua",
                            NotificationChannels = 1,
                            NotificationOffsets = "[15]",
                            Priority = 0,
                            RecurrenceRule = "FREQ=HOURLY;INTERVAL=2"
                        });
                });

            modelBuilder.Entity("mbeNote.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("mbeNote.Core.Models.CalendarConnection", b =>
                {
                    b.HasOne("mbeNote.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("mbeNote.Core.Models.PushSubscription", b =>
                {
                    b.HasOne("mbeNote.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("mbeNote.Core.Models.Reminder", b =>
                {
                    b.HasOne("mbeNote.Core.Models.ReminderCategory", "Category")
                        .WithMany("Reminders")
                        .HasForeignKey("CategoryId");

                    b.HasOne("mbeNote.Core.Models.User", "User")
                        .WithMany("Reminders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("mbeNote.Core.Models.ReminderCategory", b =>
                {
                    b.HasOne("mbeNote.Core.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("mbeNote.Core.Models.ReminderHistory", b =>
                {
                    b.HasOne("mbeNote.Core.Models.Reminder", "Reminder")
                        .WithMany("History")
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mbeNote.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reminder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("mbeNote.Core.Models.ReminderNotification", b =>
                {
                    b.HasOne("mbeNote.Core.Models.Reminder", "Reminder")
                        .WithMany("Notifications")
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mbeNote.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reminder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("mbeNote.Core.Models.ReminderShare", b =>
                {
                    b.HasOne("mbeNote.Core.Models.Reminder", "Reminder")
                        .WithMany("Shares")
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mbeNote.Core.Models.User", "SharedWithUser")
                        .WithMany()
                        .HasForeignKey("SharedWithUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reminder");

                    b.Navigation("SharedWithUser");
                });

            modelBuilder.Entity("mbeNote.Core.Models.ReminderTemplate", b =>
                {
                    b.HasOne("mbeNote.Core.Models.ReminderCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("mbeNote.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("mbeNote.Core.Models.Reminder", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Notifications");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("mbeNote.Core.Models.ReminderCategory", b =>
                {
                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("mbeNote.Core.Models.User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
